const CATEGORY = {
  STARTER: "Entrée",
  DISH: "Plat",
  DESSERT: "Dessert",
};

const COUNTRY = {
  CHINESE: "Chinois",
  FRENCH: "Français",
  AMERICAN: "Américain",
  INDOCHINESE: "Indochinois",
  VIETNAMESE: "Vietnamien",
  MAGHREBIAN: "Maghrébin",
  ITALIAN: "Italien",
  SPANISH: "Espagnol",
  FRENCH_JAPANESE: "Franco-Japonais",
};

let recipes = [
  {
    id: 1,
    category: CATEGORY.STARTER,
    name: "Oeufs de cent ans",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613243723/PXL_20201124_183850908.PORTRAIT_uk155u.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613508634/PXL_20201124_183850908.PORTRAIT_qaxreq.jpg",
    country: COUNTRY.CHINESE,
    preparationTime: "15 min",
    restTime: "30 min",
    cookingTime: "0 min",
    totalTime: "45 min",
    quantity: "Pour 6 oeufs",
    ingredients: [
      "Sucre",
      "Echalotes au vinaigre",
      "Vinaigre noir",
      "Coriandre",
    ],
    instructions: [
      "Ecaler les oeufs.",
      "Les couper en 4 dans le sens de la longueur et les disposer dans un plat.",
      "Ajouter un peu de sucre.",
      "Réserver au frais pendant 30 minutes.",
      "Laver la coriandre.",
      "Ajouter des échalotes au vinaigre dans le plat.",
      "Verser du vinaigre noir.",
      "Disposer de la coriandre par-dessus.",
    ],
  },
  {
    id: 2,
    category: CATEGORY.DISH,
    name: "Loc Lac",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613491099/PXL_20201121_182427531.PORTRAIT_1_g8defd.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613491099/PXL_20201121_182427531.PORTRAIT_1_g8defd.jpg",
    country: COUNTRY.INDOCHINESE,
    preparationTime: "20 min",
    cookingTime: "30 min",
    restTime: "1 H 00 min",
    totalTime: "1 H 50 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "500 g de merlan de boeuf",
      "3 gousses d'ail",
      "3 cs de sauce soja salée",
      "5 cs de sauce huître",
      "3 verres de riz thaï",
      "2 cs de concentré de tomates",
      "4 cs de ketchup",
      "4 oeufs",
      "1 concombre",
      "4 tomates",
      "2 oignons",
      "1 citron vert",
      "Sel",
      "Poivre",
      "Huile de tournesol",
    ],
    instructions: [
      "Couper le boeuf en cubes, émincer les gousses d'ail, puis les mettre dans un bol.",
      "Ajouter la sauce soja et la sauce huître.",
      "Mélanger et laisser mariner au frais pendant au moins 1 heure.",
      "Rincer le riz et le cuire dans un cuiseur à riz.",
      "Couper le concombre en demi-rondelles, les tomates en rondelles et les oignons en lamelles.",
      "Répartir et disposer le tout sur des assiettes.",
      "Dans un ramequin, presser le citron, ajouter du sel et du poivre, puis mélanger.",
      "Dans un wok chauffé, verser un peu d'huile de tournesol et ajouter le riz cuit.",
      "Ajouter le concentré de tomates et le ketchup, puis faire revenir le tout jusqu'à ce que le mélange soit homogène.",
      "Disposer le riz sur les assiettes.",
      "Faire revenir le boeuf dans le wok à feu vif pendant 5 minutes.",
      "Dans une poêle chauffée, verser un peu d'huile et cuire les oeufs au plat à feu moyen pendant 3 minutes.",
      "Disposer le boeuf sur les oignons et les oeufs sur le riz dans les assiettes.",
    ],
  },
  {
    id: 3,
    category: CATEGORY.DISH,
    name: "Zha Jiang Mian",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613243456/149990910_1909050255915243_2559880426026161432_n_vzjh1u.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613509187/149990910_1909050255915243_2559880426026161432_n_mxm0mu.jpg",
    country: COUNTRY.CHINESE,
    preparationTime: "30 min",
    cookingTime: "45 min",
    restTime: "0 min",
    totalTime: "1 H 15 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "5 gousses d'ail",
      "2 échalotes",
      "1 oignon",
      "400 g de palette de porc",
      "4 cs de sauce au soja salée",
      "1 cs de poivre",
      "2 cs de sucre roux",
      '1 cs de "Chen Nian Hua Tiao Wine"',
      "5 cs de sauce huître",
      "2 cs de sauce saveur abalone",
      "1 cc de Maïzena",
      "1 paquet de tofu aux 5 épices",
      "Huile de tournesol",
      '1 cs de sauce "chili bean" (Toban Djan)',
      "2 cs de sauce soja salée",
      '2 cs de sauce "mushroom dark soy sauce"',
      "1 concombre",
      "Pousses de soja",
      "Coriandre",
      "Ciboulette",
      "1 kg d'udon",
    ],
    instructions: [
      "Emincer les gousses d'ail, les échalotes et l'oignon, puis réserver.",
      "Rincer la palette de porc et la couper en morceaux.",
      "Mixer le porc avec la sauce au soja salée.",
      'Assaisonner le porc haché avec du poivre, du sucre, du vin "Chen Nian Hua Tiao", de la sauce huître, de la sauce saveur abalone et de la maïzena, puis réserver.',
      "Rincer le tofu aux 5 épices et le couper en dés, puis réserver.",
      "Dans un wok chauffé à feu vif, verser un peu d'huile de tournesol.",
      "Ajouter l'oignon, puis l'ail et les échalotes, pour les faire dorer.",
      'Ajouter la sauce "chili bean" (Toban Djan).',
      "Ajouter le porc haché.",
      "Ajouter le tofu aux 5 épices.",
      'Ajouter la sauce soja salée et la sauce "mushroom dark soy sauce".',
      "Ajouter 75 cl d'eau bouillante et laisser mijoter pendant 2 minutes.",
      "Ajouter 30 cl d'eau bouillante et laisser mijoter pendant 2 minutes.",
      "Couvrir et laisser mijoter pendant 30 minutes à feu doux.",
      "Laver et couper le concombre, les pousses de soja, la coriandre et la ciboulette.",
      "Juste avant le service, cuire les udon.",
      "Disposer les udon dans des bols, verser la sauce au porc et au tofu par-dessus, puis parsemer de concombre, de pousses de soja, de coriandre et de ciboulette.",
    ],
  },
  {
    id: 4,
    category: CATEGORY.DISH,
    name: "Phô",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613239803/PXL_20201123_114903231_imx8m2.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613509671/PXL_20201123_114903231_ljbsyr.jpg",
    country: COUNTRY.VIETNAMESE,
    preparationTime: "30 min",
    cookingTime: "3 H 00 min",
    restTime: "24 H 00 min",
    totalTime: "27 H 30 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "1 oignon",
      "1 gingembre",
      "1 queue de boeuf",
      "2 carottes",
      "1 sachet d'épices pour phô",
      "2 cubes de bouillon de boeuf",
      'Sauce de poisson "Nuoc Mam"',
      "Sel",
      "Menthe",
      "Basilic",
      "Pousses de soja",
      "Ciboule",
      "400 g de merlan",
      "500 g de vermicelles de riz pour phô",
      "1 citron vert",
      "Sauce Hoisin",
      "Sauce Satay",
    ],
    instructions: [
      "Préchauffer le four à 200 °C. Enfourner l'oignon épluché et le gingembre non pelé pendant 5 minutes.",
      "Dans une marmite, porter 3 L d'eau à ébullition, puis y plonger la queue de boeuf coupée en morceaux pendant 1 minute.",
      "Vider la marmite et la nettoyer, rincer les morceaux de queue de boeuf et les remettre dans la marmite avec 6 L d'eau, puis porter à ébullition.",
      "Couper les carottes en morceaux et les ajouter.",
      "Ajouter le sachet d'épices pour phô, 2 cubes de bouillon de boeuf, de la sauce de poisson \"Nuoc Mam\", du sel et l'oignon doré.",
      "Laver le gingembre, l'écraser et l'ajouter.",
      "Ecumer régulièrement, couvrir partiellement et laisser mijoter à feu doux pendant 3 heures.",
      "Ajouter de l'eau bouillante si nécessaire.",
      "Laisser refroidir la marmite avant de la mettre au frais pendant 24 heures.",
      "Sortir la marmite, retirer le gras à la surface du bouillon, puis réchauffer.",
      "Laver la menthe, le basilic, les pousses de soja et la ciboule, puis la ciseler.",
      "Couper le merlan en fines tranches.",
      "Cuire les vermicelles de riz pour phô et les disposer dans des bols.",
      "Disposer les tranches de merlan par-dessus.",
      "Verser le bouillon brûlant dans les bols.",
      "Parsemer de menthe, de basilic, de pousses de soja et de ciboule.",
      "Presser le citron vert dans la soupe.",
      "Dans un ramequin, mélanger la sauce Hoisin et la sauce Satay.",
    ],
  },
  {
    id: 5,
    category: CATEGORY.DISH,
    name: "Couscous",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613239750/PXL_20201027_183743640_t7rwhs.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613664527/PXL_20201027_183743640_a7eewe.jpg",
    country: COUNTRY.MAGHREBIAN,
    preparationTime: "30 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "1 H 05 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "3 carottes",
      "4 navets",
      "2 courgettes",
      "2 tomates",
      "Huile d'olive",
      "6 pilons de poulet",
      "1 cube de bouillon de boeuf",
      "3 cs de concentré de tomates",
      "1 sachet de 20 g d'épices pour couscous oriental",
      "250 g de pois chiches",
      "8 chipolatas",
      "300 g de semoule",
    ],
    instructions: [
      "Laver les carottes, les navets, les courgettes et les tomates.",
      "Eplucher les carottes et les navets.",
      "Couper tous les légumes en morceaux.",
      "Dans une marmite chauffée, verser un peu d'huile d'olive et mettre les pilons de poulet pour les faire dorer.",
      "Verser 1 L d'eau, puis ajouter les carottes, les navets, les courgettes, les tomates, le cube de bouillon de boeuf, le concentré de tomates, les épices pour couscous et les pois chiches égouttés, puis mélanger.",
      "Porter à ébullition, couvrir partiellement et laisser mijoter à feu doux pendant 35 minutes.",
      "Dans un saladier, verser autant de verres de couscous que de verres d'eau, puis couvrir et laisser gonfler.",
      "Préchauffer le four à 200 °C. Placer les chipolatas dans un plat et les enfourner pendant 20 minutes.",
      "Juste avant le service, égrener la semoule, chauffer au micro-ondes pendant 2 minutes, puis ajouter du beurre et mélanger.",
    ],
  },
  {
    id: 6,
    category: CATEGORY.DISH,
    name: "Risotto aux fruits de mer",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613247390/PXL_20201219_190638040_dqc5jb.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613247390/PXL_20201219_190638040_dqc5jb.jpg",
    country: COUNTRY.ITALIAN,
    preparationTime: "30 min",
    cookingTime: "30 min",
    restTime: "0 min",
    totalTime: "1 H 00 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "500 g de fruits de mer surgelés (crevettes, moules, encornets)",
      "8 coquilles Saint-Jacques",
      "2 échalotes",
      "Huile d'olive",
      "25 cl de vin blanc",
      "1 petite boîte de pulpe de tomates",
      "4 cc de fumet de poisson",
      "250 g de riz arborio",
      "2 cs de crème fraîche épaisse",
    ],
    instructions: [
      "Laver les fruits de mer décongelés au préalable et les coquilles Saint-Jacques.",
      "Emincer les échalotes.",
      "Dans une casserole, porter 75 cl d'eau à ébullition. Ajouter le vin blanc, la pulpe de tomates et le fumet de poisson. Mélanger, puis réserver le bouillon.",
      "Dans une sauteuse chauffée, verser un peu d'huile d'olive et cuire les coquilles Saint-Jacques pendant 1 minute de chaque côté, puis les mettre dans un saladier à l'aide d'une pince.",
      "Faire revenir les échalotes et les fruits de mer, puis les ajouter au saladier. Réserver.",
      "Dans la sauteuse, verser un peu d'huile d'olive, ajouter le riz et remuer jusqu'à ce qu'il devienne transparent.",
      "Ajouter une louche de bouillon et mélanger jusqu'à absorption du bouillon.",
      "Recommencer jusqu'à épuisement du bouillon (pendant environ 20 minutes).",
      "Ajouter les coquilles Saint-Jacques, les fruits de mer et les échalotes.",
      "Ajouter la crème fraîche épaisse.",
      "Mélanger, puis servir.",
    ],
  },
  {
    id: 7,
    category: CATEGORY.DISH,
    name: "Risotto au parmesan et aux champignons",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613250039/PXL_20201116_184513904_zjtt8k.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613250039/PXL_20201116_184513904_zjtt8k.jpg",
    country: COUNTRY.ITALIAN,
    preparationTime: "15 min",
    cookingTime: "30 min",
    restTime: "0 min",
    totalTime: "45 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "500 g de champignons",
      "1 noix de beurre",
      "1 gousse d'ail",
      "3 cs + 10 cl de vin blanc",
      "20 cl de crème fraîche liquide",
      "Sel",
      "Poivre",
      "2 cubes de bouillon de légumes",
      "Huile d'olive",
      "1 oignon",
      "250 g de riz arborio",
      "100 g de copeaux de parmesan",
      "Origan",
    ],
    instructions: [
      "Laver les champignons et les couper en morceaux.",
      "Emincer la gousse d'ail et l'oignon.",
      "Dans une casserole, faire fondre le beurre et revenir l'ail.",
      "Ajouter les champignons et les cuire pendant 3 minutes.",
      "Ajouter 3 cuillères à soupe de vin blanc et laisser cuire jusqu'à ce qu'il réduise.",
      "Ajouter la crème fraîche, du sel et du poivre. Mélanger, puis réserver.",
      "Dans une casserole, porter 1 L d'eau à ébullition. Ajouter les cubes de bouillon de légumes pour les faire diluer.",
      "Dans une sauteuse chauffée, verser un peu d'huile d'olive. Ajouter l'oignon pour le faire dorer.",
      "Ajouter le riz et remuer jusqu'à ce qu'il devienne transparent.",
      "Ajouter 10 cl de vin blanc et remuer jusqu'à ce qu'il soit absorbé par le riz.",
      "Ajouter une louche de bouillon et mélanger jusqu'à absorption du bouillon.",
      "Recommencer jusqu'à épuisement du bouillon (pendant environ 20 minutes).",
      "Ajouter la sauce aux champignons et la moitié du parmesan, puis mélanger.",
      "Servir dans des assiettes. Parsemer du reste de parmesan et d'origan.",
    ],
  },
  {
    id: 8,
    category: CATEGORY.DISH,
    name: "Paella",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613728911/PXL_20210216_182309380.PORTRAIT_o4nic4.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613729005/PXL_20210216_182309380.PORTRAIT_k7iro8.jpg",
    country: COUNTRY.SPANISH,
    preparationTime: "35 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "1 H 10 min",
    quantity: "Pour 4 personnes",
    ingredients: [
      "250 g de moules",
      "250 g d'anneaux d'encornet",
      "1 poivron",
      "3 tomates",
      "1 oignon",
      "2 gousses d'ail",
      "1 chorizo",
      "Huile d'olive",
      "6 pilons de poulet",
      "2 doses de safran",
      "Sel",
      "Poivre",
      "250 g de riz",
      "1 cube de bouillon de volaille",
      "500 g de petits pois",
      "8 crevettes cuites",
    ],
    instructions: [
      "Laver les moules, les anneaux d'encornet, le poivron et les tomates.",
      "Couper le poivron et les tomates en cubes, ainsi que le chorizo en tranches.",
      "Emincer l'oignon et les gousses d'ail.",
      "Dans une sauteuse chauffée, verser un peu d'huile d'olive et ajouter les pilons de poulet pour les faire dorer.",
      "Ajouter les anneaux d'encornet et l'oignon, puis remuer.",
      "Ajouter le poivron, les tomates, l'ail, le safran, du sel et du poivre. Cuire pendant 5 minutes en remuant.",
      "Laver le riz, puis l'ajouter.",
      "Verser 50 cl d'eau et ajouter le cube de bouillon de volaille.",
      "Ajouter les moules, le chorizo et les petits pois égouttés.",
      "Mélanger, porter à ébullition, puis couvrir et laisser mijoter à feu doux pendant 30 minutes en remuant régulièrement.",
      "10 minutes avant la fin de la cuisson, retirer le couvercle et répartir les crevettes par-dessus.",
    ],
  },
  {
    id: 9,
    category: CATEGORY.DESSERT,
    name: "Cookies aux pépites de chocolat",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613744877/20200427_165819_barwxx.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613744877/20200427_165819_barwxx.jpg",
    country: COUNTRY.AMERICAN,
    preparationTime: "20 min",
    cookingTime: "12 min",
    restTime: "0 min",
    totalTime: "32 min",
    quantity: "Pour 20 mini cookies",
    ingredients: [
      "85 g de beurre demi-sel",
      "30 g de sucre",
      "1 sachet de sucre vanillé",
      "1 oeuf",
      "150 g de farine",
      "100 g de pépites de chocolat",
    ],
    instructions: [
      "Dans un saladier, laisser le beurre ramollir à température ambiante.",
      "Ajouter le sucre et le sucre vanillé, puis mélanger avec une cuillère.",
      "Ajouter l'oeuf et mélanger.",
      "Ajouter la farine et mélanger.",
      "Ajouter les pépites de chocolat et mélanger jusqu'à obtenir une pâte.",
      "Préchauffer le four à 180 °C.",
      "Recouvrir une plaque allant au four de papier cuisson.",
      "Former des boules avec la pâte, les répartir sur la plaque en les espaçant et les aplatir très légèrement.",
      "Enfourner pendant 12 minutes jusqu'à ce que les cookies soient dorés.",
    ],
  },
  {
    id: 10,
    category: CATEGORY.DESSERT,
    name: "Fondant au chocolat",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613748985/20200617_164244_bgwuss.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613748985/20200617_164244_bgwuss.jpg",
    country: COUNTRY.FRENCH,
    preparationTime: "15 min",
    cookingTime: "25 min",
    restTime: "0 min",
    totalTime: "40 min",
    quantity: "Pour 6 personnes",
    ingredients: [
      "150 g de beurre demi-sel",
      "200 g de chocolat noir",
      "30 g de sucre",
      "3 oeufs",
      "50 g de farine",
    ],
    instructions: [
      "Préchauffer le four à 150 °C.",
      "Dans un bol, mettre le beurre et le chocolat cassé en morceaux.",
      "Faire fondre le tout au micro-ondes à 500 W de puissance pendant 45 secondes.",
      "Dans un saladier, verser le sucre, ajouter les oeufs, puis mélanger avec un fouet.",
      "Ajouter la farine et mélanger.",
      "Beurrer un moule.",
      "Ajouter le mélange beurre/chocolat dans le saladier et mélanger.",
      "Verser la pâte dans le moule.",
      "Enfourner pendant 25 minutes.",
    ],
  },
  {
    id: 11,
    category: CATEGORY.DESSERT,
    name: "Cake aux bananes et aux pépites de chocolat",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613250625/PXL_20201118_151233557.PORTRAIT_nbgupp.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613764403/PXL_20201118_151233557.PORTRAIT_nbgupp_rfwimn.jpg",
    country: COUNTRY.FRENCH,
    preparationTime: "15 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "50 min",
    quantity: "Pour 8 personnes",
    ingredients: [
      "100 g de beurre demi-sel",
      "1 sachet de sucre vanillé",
      "3 oeufs",
      "180 g de farine",
      "1 sachet de levure chimique",
      "2 bananes bien mûres",
      "100 g de pépites de chocolat",
    ],
    instructions: [
      "Préchauffer le four à 180 °C.",
      "Dans un bol, mettre le beurre et le faire fondre au micro-ondes à 500 W de puissance pendant 30 secondes.",
      "Dans un saladier, verser le sucre, ajouter les oeufs, puis mélanger avec un fouet jusqu'à obtention d'un mélange mousseux.",
      "Ajouter la farine et la levure, puis mélanger.",
      "Beurrer un moule.",
      "Ajouter le beurre fondu dans le saladier et mélanger.",
      "Eplucher les bananes, les couper en rondelles et les ajouter, puis les écraser avec une fourchette.",
      "Ajouter les pépites de chocolat et mélanger.",
      "Verser la pâte dans le moule.",
      "Enfourner pendant 35 minutes.",
    ],
  },
  {
    id: 12,
    category: CATEGORY.DESSERT,
    name: "Cake au matcha et aux framboises",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613251982/20200530_125217_fgt9ya.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613251982/20200530_125217_fgt9ya.jpg",
    country: COUNTRY.FRENCH_JAPANESE,
    preparationTime: "15 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "50 min",
    quantity: "Pour 8 personnes",
    ingredients: [
      "90 g de beurre demi-sel",
      "1 cs de matcha",
      "10 cl de lait",
      "50 g de sucre de canne",
      "3 oeufs",
      "165 g de farine",
      "1 sachet de levure chimique",
      "125 g de framboises",
    ],
    instructions: [
      "Préchauffer le four à 160 °C.",
      "Dans un bol, mettre le beurre et le faire fondre au micro-ondes à 500 W de puissance pendant 30 secondes.",
      "Dans un bol, verser le matcha et le lait, puis mélanger.",
      "Dans un saladier, verser le sucre, ajouter les oeufs, puis mélanger avec un fouet.",
      "Ajouter le mélange matcha/lait et mélanger.",
      "Ajouter la farine et la levure, puis mélanger.",
      "Beurrer un moule.",
      "Ajouter le beurre fondu dans le saladier et mélanger jusqu'à obtention d'une pâte.",
      "Verser la moitié de la pâte dans le moule. Répartir les framboises sur la surface. Verser l'autre moitié de la pâte par-dessus.",
      "Enfourner pendant 35 minutes.",
    ],
  },
  {
    id: 13,
    category: CATEGORY.DESSERT,
    name: "Cake marbré au chocolat",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613251769/20200529_151900_i5y051.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613251769/20200529_151900_i5y051.jpg",
    country: COUNTRY.FRENCH,
    preparationTime: "15 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "50 min",
    quantity: "Pour 8 personnes",
    ingredients: [
      "75 g de beurre demi-sel",
      "30 g de sucre",
      "3 oeufs",
      "240 g de farine",
      "1 sachet de levure chimique",
      "20 cl de lait",
      "200 g de chocolat noir",
    ],
    instructions: [
      "Préchauffer le four à 160 °C.",
      "Dans un bol, mettre le beurre et le faire fondre au micro-ondes à 500 W de puissance pendant 30 secondes.",
      "Dans un saladier, verser le sucre, ajouter les oeufs, puis mélanger avec un fouet.",
      "Beurrer un moule.",
      "Ajouter le beurre fondu dans le saladier et mélanger.",
      "Ajouter la farine et la levure, puis mélanger.",
      "Verser le lait et mélanger jusqu'à obtention d'une pâte.",
      "Dans un bol, casser le chocolat en morceaux et le faire fondre au micro-ondes à 500 W de puissance pendant 45 secondes.",
      "Verser la moitié de la pâte dans le moule.",
      "Ajouter le chocolat fondu à la pâte restante dans le saladier et mélanger.",
      "Verser la pâte au chocolat dans le moule.",
      "A l'aide d'un couteau, mélanger les 2 pâtes dans le moule en faisant des mouvements rapides de gauche à droite et de droite à gauche.",
      "Enfourner pendant 35 minutes.",
    ],
  },
  {
    id: 14,
    category: CATEGORY.DESSERT,
    name: "Cake aux myrtilles",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613252173/20200704_122544_wymbci.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_584/v1613252173/20200704_122544_wymbci.jpg",
    country: COUNTRY.FRENCH,
    preparationTime: "15 min",
    cookingTime: "35 min",
    restTime: "0 min",
    totalTime: "50 min",
    quantity: "Pour 8 personnes",
    ingredients: [
      "125 g de beurre demi-sel",
      "30 g de sucre de canne",
      "3 oeufs",
      "10 cl de lait",
      "250 g de farine",
      "1 sachet de levure chimique",
      "120 g de myrtilles",
    ],
    instructions: [
      "Préchauffer le four à 160 °C.",
      "Dans un bol, mettre le beurre et le faire fondre au micro-ondes à 500 W de puissance pendant 30 secondes.",
      "Dans un saladier, verser le sucre, ajouter les oeufs, puis mélanger avec un fouet.",
      "Beurrer un moule.",
      "Ajouter le beurre fondu dans le saladier et mélanger.",
      "Verser le lait et mélanger.",
      "Ajouter la farine et la levure, puis mélanger jusqu'à obtention d'une pâte.",
      "Ajouter les myrtilles et mélanger.",
      "Verser la pâte dans le moule.",
      "Enfourner pendant 35 minutes.",
    ],
  },
  {
    id: 15,
    category: CATEGORY.DESSERT,
    name: "Crêpes",
    thumbnailPictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613250373/PXL_20201101_151424265_o5xjqp.jpg",
    pictureUrl:
      "https://res.cloudinary.com/dvpcjyb48/image/upload/c_scale,w_400/v1613829214/PXL_20201101_151424265_quxnso.jpg",
    country: COUNTRY.FRENCH,
    preparationTime: "10 min",
    cookingTime: "20 min",
    restTime: "0 min",
    totalTime: "30 min",
    quantity: "Pour 12 crêpes",
    ingredients: [
      "50 g de beurre demi-sel",
      "1 sachet de sucre vanillé",
      "250 g de farine",
      "4 oeufs",
      "50 cl de lait",
    ],
    instructions: [
      "Dans un bol, mettre le beurre et le faire fondre au micro-ondes à 500 W de puissance pendant 30 secondes.",
      "Dans un saladier, mettre le sucre et la farine, puis mélanger.",
      "Ajouter les oeufs et mélanger.",
      "Verser le lait progressivement en mélangeant.",
      "Ajouter le beurre fondu et mélanger.",
      "Dans une poêle chauffée à feu doux et légèrement huilée, verser une louche de pâte et la répartir sur toute la surface en faisant un mouvement de rotation avec la poêle.",
      "Lorsque le premier côté de la crêpe est cuit, la retourner et attendre jusqu'à ce que le deuxième côté soit cuit, puis déposer la crêpe sur une assiette.",
      "Recommencer jusqu'à épuisement de la pâte.",
    ],
  },
];

export { CATEGORY, COUNTRY, recipes };
